name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.10", "3.11", "3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py') > pylint-report.txt || true
        SCORE=$(tail -n 2 pylint-report.txt | grep -oE "[0-9]+\.[0-9]+(?=/10)")
        echo "Pylint score: $SCORE"
        echo "score=$SCORE" >> $GITHUB_ENV
        if (( $(echo "$SCORE < 8.0" | bc -l) )); then
          echo "Pylint score $SCORE is below the passing threshold of 8.0"
          exit 1
        fi